//! Sanity test: with the `uniffi` feature on, the scaffolding compiles and
//! the public functions behave as the UDL declares.
//!
//! These tests intentionally exercise the *re-export surface* of
//! `mdviewer-jni` (which pulls `mdviewer-core` with `features = ["uniffi"]`)
//! rather than poking at the UniFFI scaffolding directly. The scaffolding
//! itself is generated by `uniffi::generate_scaffolding!` in this crate's
//! `build.rs` and linked in via `uniffi::include_scaffolding!` over in
//! `mdviewer-core`. Compiling + running these tests is the cheap proof that
//! the feature flag wiring + UDL parse + bindgen all hold together.

use mdviewer_core::document::RenderOptions;

#[test]
fn render_via_core_returns_html() {
    let result = mdviewer_core::document::render_markdown(
        "# Hello",
        &RenderOptions {
            syntax_highlighting: false,
            mermaid_enabled: false,
        },
    );
    assert!(
        result.html.contains("<h1"),
        "expected an <h1> in rendered HTML, got: {}",
        result.html
    );
}

#[test]
fn load_then_save_sidecar_round_trips() {
    // Empty bytes -> a fresh empty store; saving + reloading must yield an
    // equally empty store. This is the smallest end-to-end path through
    // sidecar.rs and is the surface the Kotlin side will call first.
    let store = mdviewer_core::sidecar::load_sidecar_bytes(b"").unwrap();
    let bytes = mdviewer_core::sidecar::save_sidecar_bytes(&store).unwrap();
    let restored = mdviewer_core::sidecar::load_sidecar_bytes(&bytes).unwrap();
    assert_eq!(
        store.list_threads().len(),
        restored.list_threads().len(),
        "round-tripped store should preserve thread count"
    );
}

#[test]
fn sidecar_filename_substitutes_name_token() {
    // sidecar_filename is the only string-only helper exposed via the UDL;
    // pin its behavior here so the JNI shim's re-export stays stable for
    // Kotlin call sites added in B5.
    let resolved = mdviewer_core::sidecar_path::sidecar_filename(
        "notes.md",
        "{name}.md.comments.json",
    );
    assert_eq!(resolved, "notes.md.comments.json");
}

// --- UniFFI binding-surface smoke tests --------------------------------------
//
// These exercise the wrappers in `mdviewer_core::uniffi_bindings` (the
// functions UniFFI's scaffolding actually dispatches to). Keeping them in
// this crate means they only run when `mdviewer-jni` (which enables the
// `uniffi` feature) is built — desktop `cargo test -p mdviewer` is unaffected.

#[test]
fn uniffi_render_markdown_wrapper_returns_html() {
    let result = mdviewer_core::uniffi_bindings::render_markdown(
        "# Hello".to_string(),
        RenderOptions {
            syntax_highlighting: false,
            mermaid_enabled: false,
        },
    )
    .expect("render_markdown wrapper should succeed");
    assert!(result.html.contains("<h1"));
}

#[test]
fn uniffi_sidecar_handle_round_trips_threads() {
    let handle =
        mdviewer_core::uniffi_bindings::load_sidecar_bytes(Vec::new()).expect("load empty");
    assert_eq!(handle.threads().len(), 0);
    let bytes = mdviewer_core::uniffi_bindings::save_sidecar_bytes(handle.clone())
        .expect("save round-trip");
    let restored =
        mdviewer_core::uniffi_bindings::load_sidecar_bytes(bytes).expect("reload bytes");
    assert_eq!(handle.threads().len(), restored.threads().len());
}

#[test]
fn uniffi_sidecar_filename_wrapper_matches_core() {
    let via_wrapper = mdviewer_core::uniffi_bindings::sidecar_filename(
        "doc.md".to_string(),
        "{name}.md.comments.json".to_string(),
    );
    assert_eq!(via_wrapper, "doc.md.comments.json");
}

#[test]
fn uniffi_core_error_wraps_anyhow() {
    // Any anyhow::Error must funnel into CoreError::Internal so the UDL's
    // [Throws=CoreError] contract holds for every internal failure mode.
    let err: mdviewer_core::uniffi_bindings::CoreError =
        anyhow::anyhow!("boom").into();
    let msg = format!("{err}");
    assert!(msg.contains("internal"), "got: {msg}");
    assert!(msg.contains("boom"), "got: {msg}");
}
