//! UniFFI-bound JNI shim. Re-exports `mdviewer_core` (built with the
//! `uniffi` feature on) so `cargo-ndk` produces an `.so` that the
//! UniFFI-generated Kotlin bindings can dlopen at runtime.
//!
//! ## Why this crate exists separately from mdviewer-core
//!
//! `crate-type = ["cdylib"]` is what UniFFI's Kotlin bindings dlopen, but
//! marking `mdviewer-core` itself as a cdylib would force the desktop's
//! `src-tauri` build (which depends on `mdviewer-core` as an rlib) to also
//! produce a cdylib, doubling link time and bundle bloat. By giving the
//! Android target its own thin wrapper crate we keep `mdviewer-core` as a
//! pure rlib for desktop while still emitting the Android-shaped output
//! here.
//!
//! The wrapper is intentionally a single `pub use`: every public function
//! and type the UDL references resolves through `mdviewer_core::*`, and
//! the scaffolding generated by `build.rs` links against those symbols
//! via `mdviewer_core`'s `include_scaffolding!` invocation.

pub use mdviewer_core::*;
