// AUTO-GENERATED by `cargo run --bin export_types`. Do not edit by hand.
// Source of truth lives in src-tauri/src/*.rs `#[derive(TS)]` blocks.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildInfo = { version: string, commit_hash: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Theme = "light" | "dark" | "follow_system";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalChangeBehavior = "ask" | "reload" | "ignore";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoMergeMode = "always" | "ask" | "manual";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartupMode = "clean" | "restore";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DarkVariant = "pure" | "cool";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSettings = { user_id: string, display_name: string, color: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DarkVariant } from "./DarkVariant";
import type { StartupMode } from "./StartupMode";
import type { Theme } from "./Theme";

export type AppearanceSettings = { theme: Theme, font_size_px: number, line_height: number, density: string, 
/**
 * Startup behavior — "clean" (boot empty) or "restore" (re-open
 * previously open tabs). `serde(default)` so settings.toml files
 * written by older app versions (no startup_mode key) deserialize
 * without error and pick up the safe default.
 */
startup_mode: StartupMode, 
/**
 * Sub-variant for the dark palette. Defaults to `Pure` (near-black);
 * `Cool` is a slightly bluish alternative. `serde(default)` keeps
 * older settings.toml files (without this key) loading cleanly.
 */
dark_variant: DarkVariant, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-tier autosave settings. Today only the SSH tier is configurable here;
 * local autosave still lives at [`EditorSettings::auto_save`] (kept stable
 * so existing settings.toml files don't drift).
 */
export type AutosaveSettings = { 
/**
 * Debounce interval for the SSH autosave loop, in milliseconds. Clamped
 * to `[5_000, 600_000]` in `clamp()` so a fat-fingered config can't
 * hammer the link or silently lose edits across disconnects.
 */
ssh_interval_ms: number, 
/**
 * Whether to autosave SSH-backed documents at all. Independent of the
 * local `auto_save` toggle — see the struct doc.
 */
ssh_enabled: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutosaveSettings } from "./AutosaveSettings";
import type { ExternalChangeBehavior } from "./ExternalChangeBehavior";

export type EditorSettings = { default_open_mode: string, auto_save: boolean, auto_save_debounce_ms: number, external_change_behavior: ExternalChangeBehavior, syntax_highlighting: boolean, mermaid_enabled: boolean, show_whitespace: boolean, word_wrap: boolean, 
/**
 * SSH autosave knobs. Lives in its own sub-struct so users can disable
 * SSH autosave without affecting local autosave (Decision 6 — a 50 MB
 * markdown over a tethered hotspot shouldn't force you to choose
 * between "lose local autosave too" and "burn the data plan").
 * `serde(default)` keeps legacy settings.toml files (no `[editor.autosave]`
 * block) loading cleanly.
 */
autosave: AutosaveSettings, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoMergeMode } from "./AutoMergeMode";

export type CommentsSettings = { auto_merge: AutoMergeMode, reattachment_confidence: number, sidecar_pattern: string, show_resolved: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { sync_provider: string | null, verbose_logs: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendMode = "auto" | "always_sidecar" | "always_drive";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendMode } from "./BackendMode";

export type DriveSettings = { feature_enabled: boolean, connected: boolean, account_email: string | null, backend_mode: BackendMode, poll_interval_active_secs: bigint, poll_interval_unfocused_secs: bigint, custom_oauth_client_id: string | null, 
/**
 * C2: once the user successfully connects to Drive for the first time,
 * this flips to `true` to globally suppress the Drive-detect toast on
 * future opens. Declared here in A1 so C2 (which only modifies frontend
 * + doc_prefs files) can rely on the field already existing.
 */
detect_toast_suppressed: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveSettings } from "./DriveSettings";

export type CloudSettings = { drive: DriveSettings, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { CloudSettings } from "./CloudSettings";
import type { CommentsSettings } from "./CommentsSettings";
import type { EditorSettings } from "./EditorSettings";
import type { OnboardingState } from "./OnboardingState";
import type { ProfileSettings } from "./ProfileSettings";

export type Settings = { profile: ProfileSettings, appearance: AppearanceSettings, editor: EditorSettings, comments: CommentsSettings, advanced: AdvancedSettings, shortcuts: { [key: string]: string }, cloud: CloudSettings, onboarding: OnboardingState, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderOptions = { syntax_highlighting: boolean, mermaid_enabled: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderResult = { html: string, 
/**
 * All `(start, end)` source offsets emitted as `data-src-offset` /
 * `data-src-end` on inline carrier elements. Useful for the round-trip
 * property test. The frontend does not consume this field; it is marked
 * `#[serde(default)]` so future schema-trim changes don't break the IPC
 * payload.
 */
text_spans: Array<[number, number]>, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveOutcome = { "kind": "ok", etag: string | null, } | { "kind": "conflict", local: string, remote: string, drive_source: string | null, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Anchor = { 
/**
 * Byte offset of the exact match's start in the most recently saved source.
 */
start: number, 
/**
 * Byte offset of the exact match's end (exclusive).
 */
end: number, 
/**
 * The selected text verbatim.
 */
exact: string, 
/**
 * Up to ~32 chars of context preceding `exact` for disambiguation.
 */
prefix: string, 
/**
 * Up to ~32 chars of context following `exact` for disambiguation.
 */
suffix: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveOutcome = { "kind": "resolved", start: number, end: number, } | { "kind": "orphan" };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { id: string, author: string, color: string, body: string, 
/**
 * RFC3339-ish timestamp; the exact format is opaque to consumers and only
 * needs to be sortable lexicographically (which the `{secs}Z` form is).
 */
created_at: string, 
/**
 * Drive-side author email (None for local-only comments). Used by C1's
 * collaborator-avatar matching.
 */
author_email: string | null, 
/**
 * Drive-side comment id (None for offline-queued comments awaiting
 * replay). Used by B6's Pending pill.
 */
drive_id: string | null, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { Comment } from "./Comment";

export type Thread = { id: string, anchor: Anchor, comments: Array<Comment>, resolved: boolean, resolved_at: string | null, resolved_by: string | null, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewComment = { author: string, color: string, body: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { NewComment } from "./NewComment";

export type NewThread = { anchor: Anchor, first_comment: NewComment, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type OpenResult = { tab_id: string, path: string, html: string, 
/**
 * Raw markdown source. Needed by Edit mode (B4) which mounts a
 * textarea seeded with this; the View↔Edit toggle silently no-ops
 * when source is missing.
 */
source: string, threads: Array<Thread>, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenResult } from "./OpenResult";

export type OpenOutcome = { "kind": "document" } & OpenResult | { "kind": "conflict", tab_id: string, path: string, local: string, incoming: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-shaped projection of `Tab` for `list_open_documents`. The frontend
 * needs both the opaque id (for activate/close) and the on-disk path (for
 * the tab label). Returning bare ids was the regression where tab labels
 * rendered the UUID instead of the filename.
 */
export type TabSummary = { id: string, path: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HunkKind = "conflicting" | "added" | "removed";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkKind } from "./HunkKind";

export type Hunk = { kind: HunkKind, local_text: string, incoming_text: string, 
/**
 * Line range in `local` as (start_inclusive, end_exclusive).
 */
local_range: [number, number], 
/**
 * Line range in `incoming` as (start_inclusive, end_exclusive).
 */
incoming_range: [number, number], };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C3: result of `export_document` — the destination folder plus the
 * filenames that landed in it. The share dialog displays these so the
 * user can confirm the export before sharing the folder by hand.
 */
export type ExportResult = { folder: string, files: Array<string>, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntryKind = "local" | "ssh";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

/**
 * One entry in the most-recently-used list, augmented with the file's
 * last-modified mtime (Unix seconds) so the StartPage can render
 * wireframe-01's "when" column ("2 hours ago", "Yesterday", "Mar 14")
 * without a follow-up IPC per row.
 *
 * `mtime` is `None` when the file was unreadable at list time (deleted,
 * permission denied) — the frontend renders `—` in that case.
 *
 * `kind` is derived at materialization time by sniffing the path's prefix —
 * `ssh://` URLs land as [`EntryKind::Ssh`], everything else is
 * [`EntryKind::Local`]. It is intentionally **not** stored on disk: keeping
 * the on-disk schema as a bare `[String, ...]` means old recents.json files
 * load unchanged and a future migration mangling kind-vs-path can't drift.
 */
export type RecentEntry = { path: string, mtime: bigint | null, kind: EntryKind, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-document override carried across the IPC boundary — see
 * `src/bin/export_types.rs::export_all` for the type-export wiring.
 *
 * Originally hosted only the per-document font-size override; C2 adds
 * `drive_detect_dismissed` so the Drive-detect toast (wireframe 08) can
 * remember a per-file "Not now" without rolling its own JSON file. Both
 * fields are `#[serde(default)]` so legacy on-disk entries written before
 * either field existed deserialise cleanly with the missing field at its
 * type default.
 */
export type DocPref = { font_size_px: number, 
/**
 * C2: once the user clicks "Not now" on the Drive-detect toast for
 * this file, the flag flips to `true` so the toast never re-appears
 * for the same file. Per-file (not global) by design — a user who
 * dismisses for `notes.md` should still see the toast on
 * `tax-2024.md` if it also lives under the Drive Desktop mount.
 * Defaults `false` and is `#[serde(default)]` so doc_prefs.json
 * files written by older app versions parse without error.
 */
drive_detect_dismissed: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabBackend = "local" | "drive_desktop" | "drive_api";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriveStatus = { connected: boolean, account_email: string | null, online: boolean, pending_count: number, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriveCollaborator = { display_name: string, email_address: string, };
