// AUTO-GENERATED by `cargo run --bin export_types`. Do not edit by hand.
// Source of truth lives in src-tauri/src/*.rs `#[derive(TS)]` blocks.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildInfo = { version: string, commit_hash: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Theme = "light" | "dark" | "follow_system";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalChangeBehavior = "ask" | "reload" | "ignore";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoMergeMode = "always" | "ask" | "manual";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSettings = { user_id: string, display_name: string, color: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type AppearanceSettings = { theme: Theme, font_size_px: number, line_height: number, density: string, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalChangeBehavior } from "./ExternalChangeBehavior";

export type EditorSettings = { default_open_mode: string, auto_save: boolean, auto_save_debounce_ms: number, external_change_behavior: ExternalChangeBehavior, syntax_highlighting: boolean, mermaid_enabled: boolean, show_whitespace: boolean, word_wrap: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoMergeMode } from "./AutoMergeMode";

export type CommentsSettings = { auto_merge: AutoMergeMode, reattachment_confidence: number, sidecar_pattern: string, show_resolved: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { sync_provider: string | null, verbose_logs: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { CommentsSettings } from "./CommentsSettings";
import type { EditorSettings } from "./EditorSettings";
import type { ProfileSettings } from "./ProfileSettings";

export type Settings = { profile: ProfileSettings, appearance: AppearanceSettings, editor: EditorSettings, comments: CommentsSettings, advanced: AdvancedSettings, shortcuts: { [key: string]: string }, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderOptions = { syntax_highlighting: boolean, mermaid_enabled: boolean, };
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderResult = { html: string, 
/**
 * All `(start, end)` source offsets emitted as `data-src-offset` /
 * `data-src-end` on inline carrier elements. Useful for the round-trip
 * property test. The frontend does not consume this field; it is marked
 * `#[serde(default)]` so future schema-trim changes don't break the IPC
 * payload.
 */
text_spans: Array<[number, number]>, };
