/**
 * Out-of-band SSH write helper for the conflict spec (24).
 *
 * Spec 24's "out-of-band rewrite triggers Conflict modal" scenario needs
 * a way to mutate the remote file WITHOUT going through our production
 * transport, so the app's pre-save SHA-256 probe sees a divergent hash
 * and the save_back path returns Conflict. This helper shells out to
 * the system `ssh` client with the committed fixture keypair and runs
 * `cat > <remotePath>` over stdin.
 *
 * Mirror of `independentSshRead.ts` — kept as a sibling file so spec 24
 * can `import { independentSshWrite } from './helpers/independentSshWrite'`
 * symmetrically with spec 23's read helper.
 */
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const FIXTURE_ROOT = path.resolve(__dirname, '../../src-tauri/tests/fixtures/ssh');

export interface IndependentSshWriteOpts {
  host: string;
  port: number;
  user: string;
  identityFile?: string;
  /** Absolute path on the remote. Single-quoted in the remote `sh -c`. */
  remotePath: string;
}

/**
 * Construct the ssh argv. Exported for vitest — same rationale as
 * `composeSshReadArgs`: pin the option set so a future edit can't drop
 * a critical flag.
 *
 * NOTE: the `contents` parameter is NOT part of argv (it goes over
 * stdin), so this fn takes the same shape as `composeSshReadArgs`.
 */
export function composeSshWriteArgs(opts: IndependentSshWriteOpts): string[] {
  const identityFile = opts.identityFile ?? path.join(FIXTURE_ROOT, 'id_test');
  // Single-quote the remote path so spaces / hyphens in the tmpdir name
  // don't break the remote shell parse. The path is generated by
  // `os.tmpdir() + mkdtempSync` and is normally well-behaved, but the
  // tmpdir on macOS is `/var/folders/<...>/T/` which has hyphens and
  // is safe inside single quotes regardless.
  const escapedPath = opts.remotePath.replace(/'/g, `'\\''`);
  return [
    '-i', identityFile,
    '-o', 'IdentitiesOnly=yes',
    '-o', 'UserKnownHostsFile=/dev/null',
    '-o', 'StrictHostKeyChecking=no',
    '-o', 'LogLevel=ERROR',
    '-p', String(opts.port),
    `${opts.user}@${opts.host}`,
    '--',
    'sh', '-c', `cat > '${escapedPath}'`,
  ];
}

export interface IndependentSshWriteInvocation extends IndependentSshWriteOpts {
  contents: string;
}

/**
 * Spawn `ssh ... -- sh -c "cat > <remotePath>"` and pipe `contents`
 * into stdin. Resolves on a clean zero-exit. Throws (with stderr) on
 * non-zero exit.
 */
export async function independentSshWrite(opts: IndependentSshWriteInvocation): Promise<void> {
  const argv = composeSshWriteArgs(opts);
  return new Promise((resolve, reject) => {
    const child = spawn('ssh', argv, { stdio: ['pipe', 'pipe', 'pipe'] });
    const stderr: Buffer[] = [];
    child.stderr.on('data', (c) => stderr.push(c));
    child.once('error', reject);
    child.once('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(
          new Error(
            `ssh write exited ${code}; stderr=${Buffer.concat(stderr).toString('utf8').trim()}`,
          ),
        );
      }
    });
    child.stdin.write(opts.contents);
    child.stdin.end();
  });
}
